version: "3.10"

services:
  postgres_container:
    image: postgres:latest
    container_name: postgres_container
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

  app:
    build: .
    volumes:
      - .:/app
    container_name: blog_application_container
    ports:
      - 8000:8000
    image: app:blog_application
    command: bash -c "apt-get update && apt-get install -y postgresql-client && until pg_isready -h postgres_container -U postgres; do sleep 1; done && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env
    depends_on:
      - postgres_container

volumes:
  postgres_data:
